### Changes

_Describe what was added, modified or removed and for what purpose

### Testing

_Explain how can this change be tested it it's not clear based on unit tests_

### Checklist

#### Source code and docs
- [ ] Changelog is updated (fixes section for a bug, changes for anything that has been added / modified/ removed)
- [ ] New code is covered by unit tests
- [ ] Added ktdoc and updated README.md if API has changed
- [ ] Made sure that unit tests pass
- [ ] Made sure that `ktlintCheck` and `detekt` tasks produce no issues

### Reviewer Checklist
- [ ] Library builds
- [ ] Changes work as expected
- [ ] Changelog and documentation updates reflect the modification made in this PR
